import Head from 'next/head'
import Image from 'next/image'
import { Bandge } from '@/shared/components/Bandge'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import axios from 'axios'
import moment from 'moment'



export default function Home() {
  const [blogs, serBlogs] = useState([])

  async function getBlogs() {
        const response = await axios.get('http://localhost:8000/api/blogs');
        serBlogs(response.data.data);
    }
  const myLoader = ({ src, width, quality }: any) => {
    return src
  }

  useEffect(()=>{
    getBlogs();
  }, []);

  return (
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <div className='flex justify-center '>
        <div className=' grid xl:grid-cols-3 lg:grid-cols-2 md:grid-cols-2 gap-5 mt-10'>
           {blogs.map((blog :any, index) => (
              <div key={index} className="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                  <Link href={`/detail/${blog.id}`}>
                      <Image loader={myLoader(blog.image)}  className="rounded-t-lg" src={blog.image} width={1920} height={1080}  alt="img" />
                  </Link>
                  <div className="p-5">
                      <Link href={`/detail/${blog.id}`}>
                          <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white hover:underline">{blog.title}</h5>
                      </Link>
                      <div className='mt-5'>
                       {
                          blog.categories.map((cat: any, index: any) => (
                            <Bandge key={index} category={cat.category}/>
                          ))
                        }
                      </div>
                      <div className='mt-5'>
                        <span className="bg-gray-200 text-gray-800 text-xs font-medium inline-flex items-center px-2.5 py-0.5 rounded mr-2 dark:bg-gray-700 dark:text-gray-400 border border-gray-300">
                          <svg aria-hidden="true" className="w-3 h-3 mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clipRule="evenodd"></path></svg>
                          {moment(blog.created_at).fromNow()}
                        </span>
                      </div>
                  </div>
                  <div className='flex justify-between p-5'>
                  <Link href={`/detail/${blog.id}`} className="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                          Read more
                          <svg aria-hidden="true" className="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clipRule="evenodd"></path></svg>
                  </Link>
                  </div>
              </div>
            ))}
         
        </div>
      </div>
    </>
  )
}
